terraform {
  required_version = ">= 1.6.0"

  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 5.0"
    }
    neon = {
      source  = "kislerdm/neon"
      version = "~> 0.13"
    }
  }

  # Remote state in Cloudflare R2 (S3-compatible). Per-tenant.
  # `bucket` and `endpoints` come from `infra/tenants/<tenant>/backend.tfvars`,
  # generated by `infra/scripts/bootstrap-state.sh <tenant>`.
  # Workspaces (dev/production) handle environments within a single tenant.
  #
  #   tofu init -reconfigure -backend-config=../tenants/<tenant>/backend.tfvars
  #
  backend "s3" {
    key                         = "terraform.tfstate"
    region                      = "auto"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    use_path_style              = true
    bucket = "app-tfstate"
    endpoints = {
      s3 = "https://<account-id>.r2.cloudflarestorage.com"
    }
  }
}
